[mypy]
python_version = 3.14
files = custom_components/meshtastic
exclude = ^custom_components/meshtastic/aiomeshtastic/protobuf/
namespace_packages = True
explicit_package_bases = True
ignore_missing_imports = True
